-- CRC › Entregas: Comitê de Entrega dos empreendimentos (antes um HTML avulso, "Habitat · Gestão
-- de Entrega", que guardava tudo no localStorage do navegador).
--
--   app_crc_areas            Áreas responsáveis (settings.responsibles). Nome em MAIÚSCULAS;
--                            "OBRA/JURIDICO" é uma área só.
--   app_crc_modelos          Modelos de projeto: só a estrutura (blocos › ações › áreas) em jsonb.
--                            "tpl_base" (Casa Laguna) é o modelo padrão e não pode ser excluído.
--   app_crc_projetos         Projeto = empreendimento (committee do HTML), ligado a uma empresa
--                            do Sienge: o acesso segue o acesso por empresa do perfil.
--   app_crc_obra_historico   % de obra por data (obraHistory). O último registro é o % atual.
--   app_crc_blocos           Blocos do projeto, na ordem de exibição (posicao).
--   app_crc_decisoes         Decisões de reunião registradas no bloco (block.notes).
--   app_crc_acoes            Ações/atividades do bloco: status, prazos, observação, marco ⭐.
--   app_crc_acao_historico   Histórico de cada ação (quem, quando, evento, nota). Só cresce.
--   app_crc_anexos           Anexos das ações; o arquivo fica no bucket privado app-crc-entregas.
--
-- Os ids são texto e vêm do próprio app ("c_xxxxxxxx", "b_…", "a_…"), como no HTML: assim o
-- backup JSON do HTML é importado sem trocar ids. Histórico, decisões, % de obra e anexos usam
-- "<id do pai>:<id do item>".
--
-- Acesso: ler exige a permissão crc.entregas (ver) e acesso à empresa do projeto; gravar exige
-- crc.entregas (editar) e acesso à empresa. As tabelas filhas carregam projeto_id e uma FK
-- composta com o pai, então um registro nunca aponta para um pai de outro projeto.

-- ---------- áreas ----------
create table if not exists public.app_crc_areas (
  nome text primary key check (length(trim(nome)) > 0 and nome = upper(nome)),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  atualizado_por uuid references auth.users (id) on delete set null
);

-- ---------- modelos ----------
create table if not exists public.app_crc_modelos (
  id text primary key,
  nome text not null check (length(trim(nome)) > 0),
  base boolean not null default false,
  -- [{"name": "BLOCO", "actions": [{"name": "AÇÃO", "resps": ["OBRA"]}]}]
  estrutura jsonb not null default '[]'::jsonb check (jsonb_typeof(estrutura) = 'array'),
  criado_em timestamptz not null default now(),
  criado_por uuid default auth.uid() references auth.users (id) on delete set null,
  atualizado_em timestamptz not null default now(),
  atualizado_por uuid references auth.users (id) on delete set null
);

create or replace function public.app_crc_modelos_protege_base()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.base then
    raise exception 'O modelo padrão não pode ser excluído.';
  end if;
  return old;
end;
$$;
revoke all on function public.app_crc_modelos_protege_base() from public, anon, authenticated;

drop trigger if exists app_crc_modelos_protege_base on public.app_crc_modelos;
create trigger app_crc_modelos_protege_base
  before delete on public.app_crc_modelos
  for each row execute function public.app_crc_modelos_protege_base();

-- ---------- projetos ----------
create table if not exists public.app_crc_projetos (
  id text primary key,
  company_id integer not null,
  nome text not null check (length(trim(nome)) > 0),
  data_entrega date,
  data_inicio date,
  unidades integer check (unidades is null or unidades >= 0),
  concluido boolean not null default false,
  concluido_em timestamptz,
  suspenso boolean not null default false,
  suspenso_em timestamptz,
  motivo_suspensao text,
  criado_em timestamptz not null default now(),
  criado_por uuid default auth.uid() references auth.users (id) on delete set null,
  atualizado_em timestamptz not null default now(),
  atualizado_por uuid references auth.users (id) on delete set null
);
create index if not exists app_crc_projetos_company_idx on public.app_crc_projetos (company_id);

create table if not exists public.app_crc_obra_historico (
  id text primary key,
  projeto_id text not null references public.app_crc_projetos (id) on delete cascade,
  data date not null,
  pct numeric(6, 2) not null check (pct >= 0 and pct <= 100),
  nota text not null default '',
  ordem bigint generated by default as identity
);
create index if not exists app_crc_obra_historico_projeto_idx on public.app_crc_obra_historico (projeto_id);

-- ---------- blocos e decisões ----------
create table if not exists public.app_crc_blocos (
  id text primary key,
  projeto_id text not null references public.app_crc_projetos (id) on delete cascade,
  nome text not null check (length(trim(nome)) > 0),
  posicao integer not null default 0,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  atualizado_por uuid references auth.users (id) on delete set null,
  unique (id, projeto_id)
);
create index if not exists app_crc_blocos_projeto_idx on public.app_crc_blocos (projeto_id);

create table if not exists public.app_crc_decisoes (
  id text primary key,
  projeto_id text not null,
  bloco_id text not null,
  quando timestamptz not null default now(),
  texto text not null,
  criado_por uuid default auth.uid() references auth.users (id) on delete set null,
  ordem bigint generated by default as identity,
  foreign key (bloco_id, projeto_id) references public.app_crc_blocos (id, projeto_id) on delete cascade
);
create index if not exists app_crc_decisoes_bloco_idx on public.app_crc_decisoes (bloco_id);

-- ---------- ações ----------
create table if not exists public.app_crc_acoes (
  id text primary key,
  projeto_id text not null,
  bloco_id text not null,
  posicao integer not null default 0,
  nome text not null check (length(trim(nome)) > 0),
  -- nomes de app_crc_areas, na ordem escolhida (renomear a área atualiza as ações pelo app)
  areas text[] not null default '{}',
  status text not null default 'NÃO INICIADO'
    check (status in ('NÃO INICIADO', 'EM ANDAMENTO', 'CONCLUÍDO', 'NÃO SE APLICA')),
  inicio date,
  prazo date,
  conclusao_real date,
  obs text not null default '',
  marco boolean not null default false,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  atualizado_por uuid references auth.users (id) on delete set null,
  unique (id, projeto_id),
  foreign key (bloco_id, projeto_id) references public.app_crc_blocos (id, projeto_id) on delete cascade
);
create index if not exists app_crc_acoes_bloco_idx on public.app_crc_acoes (bloco_id);
create index if not exists app_crc_acoes_projeto_idx on public.app_crc_acoes (projeto_id);

create table if not exists public.app_crc_acao_historico (
  id text primary key,
  projeto_id text not null,
  acao_id text not null,
  quando timestamptz not null default now(),
  -- CRIADO, EDIÇÃO, REPLANEJAMENTO, STATUS, CONCLUSÃO, CONCLUSÃO COM ATRASO, COMENTÁRIO, ANEXO,
  -- RISCO (e os antigos EDICAO / RENOMEACAO vindos do HTML)
  evento text not null,
  nota text not null default '',
  -- nome de quem fez (o HTML gravava o nome digitado em Configurações)
  usuario text not null default '',
  usuario_id uuid default auth.uid() references auth.users (id) on delete set null,
  ordem bigint generated by default as identity,
  foreign key (acao_id, projeto_id) references public.app_crc_acoes (id, projeto_id) on delete cascade
);
create index if not exists app_crc_acao_historico_acao_idx on public.app_crc_acao_historico (acao_id);
create index if not exists app_crc_acao_historico_quando_idx on public.app_crc_acao_historico (quando);

create table if not exists public.app_crc_anexos (
  id text primary key,
  projeto_id text not null,
  acao_id text not null,
  nome text not null,
  mime text not null default '',
  tamanho bigint not null default 0,
  -- caminho no bucket app-crc-entregas: <projeto_id>/<acao_id>/<id do anexo>-<nome>
  storage_path text not null,
  adicionado_em timestamptz not null default now(),
  criado_por uuid default auth.uid() references auth.users (id) on delete set null,
  foreign key (acao_id, projeto_id) references public.app_crc_acoes (id, projeto_id) on delete cascade
);
create index if not exists app_crc_anexos_acao_idx on public.app_crc_anexos (acao_id);

-- ---------- auditoria ----------
do $$
declare
  t text;
begin
  foreach t in array array['app_crc_areas', 'app_crc_modelos', 'app_crc_projetos', 'app_crc_blocos', 'app_crc_acoes'] loop
    execute format('drop trigger if exists %I on public.%I', t || '_auditoria', t);
    execute format('create trigger %I before insert or update on public.%I for each row execute function public.app_set_auditoria()', t || '_auditoria', t);
  end loop;
end;
$$;

-- ---------- acesso ----------
-- Projeto visível/gravável pelo usuário logado: permissão crc.entregas + acesso à empresa.
create or replace function public.app_crc_acesso(p_projeto text, p_editar boolean default false)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select app_pode('crc.entregas', p_editar)
     and exists (select 1 from app_crc_projetos p where p.id = p_projeto and app_pode_empresa(p.company_id));
$$;
revoke all on function public.app_crc_acesso(text, boolean) from public, anon;
grant execute on function public.app_crc_acesso(text, boolean) to authenticated;

alter table public.app_crc_areas enable row level security;
alter table public.app_crc_modelos enable row level security;
alter table public.app_crc_projetos enable row level security;
alter table public.app_crc_obra_historico enable row level security;
alter table public.app_crc_blocos enable row level security;
alter table public.app_crc_decisoes enable row level security;
alter table public.app_crc_acoes enable row level security;
alter table public.app_crc_acao_historico enable row level security;
alter table public.app_crc_anexos enable row level security;

do $$
declare
  t text;
begin
  -- Cadastros do módulo (sem empresa)
  foreach t in array array['app_crc_areas', 'app_crc_modelos'] loop
    execute format('drop policy if exists %I on public.%I', t || '_select', t);
    execute format('create policy %I on public.%I for select to authenticated using (public.app_is_member() and public.app_pode(''crc.entregas''))', t || '_select', t);
    execute format('drop policy if exists %I on public.%I', t || '_insert', t);
    execute format('create policy %I on public.%I for insert to authenticated with check (public.app_pode(''crc.entregas'', true))', t || '_insert', t);
    execute format('drop policy if exists %I on public.%I', t || '_update', t);
    execute format('create policy %I on public.%I for update to authenticated using (public.app_pode(''crc.entregas'', true)) with check (public.app_pode(''crc.entregas'', true))', t || '_update', t);
    execute format('drop policy if exists %I on public.%I', t || '_delete', t);
    execute format('create policy %I on public.%I for delete to authenticated using (public.app_pode(''crc.entregas'', true))', t || '_delete', t);
  end loop;

  -- Projetos: empresa do próprio registro
  t := 'app_crc_projetos';
  execute format('drop policy if exists %I on public.%I', t || '_select', t);
  execute format('create policy %I on public.%I for select to authenticated using (public.app_is_member() and public.app_pode(''crc.entregas'') and public.app_pode_empresa(company_id))', t || '_select', t);
  execute format('drop policy if exists %I on public.%I', t || '_insert', t);
  execute format('create policy %I on public.%I for insert to authenticated with check (public.app_pode(''crc.entregas'', true) and public.app_pode_empresa(company_id))', t || '_insert', t);
  execute format('drop policy if exists %I on public.%I', t || '_update', t);
  execute format('create policy %I on public.%I for update to authenticated using (public.app_pode(''crc.entregas'', true) and public.app_pode_empresa(company_id)) with check (public.app_pode(''crc.entregas'', true) and public.app_pode_empresa(company_id))', t || '_update', t);
  execute format('drop policy if exists %I on public.%I', t || '_delete', t);
  execute format('create policy %I on public.%I for delete to authenticated using (public.app_pode(''crc.entregas'', true) and public.app_pode_empresa(company_id))', t || '_delete', t);

  -- Filhas: acesso ao projeto
  foreach t in array array['app_crc_obra_historico', 'app_crc_blocos', 'app_crc_decisoes', 'app_crc_acoes', 'app_crc_acao_historico', 'app_crc_anexos'] loop
    execute format('drop policy if exists %I on public.%I', t || '_select', t);
    execute format('create policy %I on public.%I for select to authenticated using (public.app_crc_acesso(projeto_id))', t || '_select', t);
    execute format('drop policy if exists %I on public.%I', t || '_insert', t);
    execute format('create policy %I on public.%I for insert to authenticated with check (public.app_crc_acesso(projeto_id, true))', t || '_insert', t);
    execute format('drop policy if exists %I on public.%I', t || '_update', t);
    execute format('create policy %I on public.%I for update to authenticated using (public.app_crc_acesso(projeto_id, true)) with check (public.app_crc_acesso(projeto_id, true))', t || '_update', t);
    execute format('drop policy if exists %I on public.%I', t || '_delete', t);
    execute format('create policy %I on public.%I for delete to authenticated using (public.app_crc_acesso(projeto_id, true))', t || '_delete', t);
  end loop;

  foreach t in array array['app_crc_areas', 'app_crc_modelos', 'app_crc_projetos', 'app_crc_obra_historico', 'app_crc_blocos',
                           'app_crc_decisoes', 'app_crc_acoes', 'app_crc_acao_historico', 'app_crc_anexos'] loop
    execute format('revoke all on table public.%I from anon, authenticated', t);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', t);
  end loop;
end;
$$;

-- ---------- carga da tela ----------
-- Tudo o que o usuário pode ver, numa chamada só (o histórico passa fácil das 1000 linhas do PostgREST).
create or replace function public.app_crc_carregar()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_proj text[];
begin
  perform app_require_auth();
  if not (app_is_member() and app_pode('crc.entregas')) then
    raise exception 'Sem permissão para CRC › Entregas.' using errcode = '42501';
  end if;
  select coalesce(array_agg(p.id), '{}') into v_proj
  from app_crc_projetos p
  where app_pode_empresa(p.company_id);

  return jsonb_build_object(
    'areas', coalesce((select jsonb_agg(a.nome order by a.nome) from app_crc_areas a), '[]'::jsonb),
    'modelos', coalesce((select jsonb_agg(jsonb_build_object('id', m.id, 'nome', m.nome, 'base', m.base, 'estrutura', m.estrutura)
                                          order by m.base desc, m.criado_em, m.id) from app_crc_modelos m), '[]'::jsonb),
    'projetos', coalesce((select jsonb_agg(to_jsonb(p) - 'criado_por' - 'atualizado_por' order by p.criado_em, p.id)
                          from app_crc_projetos p where p.id = any(v_proj)), '[]'::jsonb),
    'obra', coalesce((select jsonb_agg(to_jsonb(o) order by o.data, o.ordem)
                      from app_crc_obra_historico o where o.projeto_id = any(v_proj)), '[]'::jsonb),
    'blocos', coalesce((select jsonb_agg(jsonb_build_object('id', b.id, 'projeto_id', b.projeto_id, 'nome', b.nome, 'posicao', b.posicao)
                                         order by b.posicao, b.criado_em)
                        from app_crc_blocos b where b.projeto_id = any(v_proj)), '[]'::jsonb),
    'decisoes', coalesce((select jsonb_agg(jsonb_build_object('id', d.id, 'bloco_id', d.bloco_id, 'quando', d.quando, 'texto', d.texto)
                                           order by d.quando, d.ordem)
                          from app_crc_decisoes d where d.projeto_id = any(v_proj)), '[]'::jsonb),
    'acoes', coalesce((select jsonb_agg(jsonb_build_object('id', a.id, 'bloco_id', a.bloco_id, 'posicao', a.posicao, 'nome', a.nome,
                                                           'areas', a.areas, 'status', a.status, 'inicio', a.inicio, 'prazo', a.prazo,
                                                           'conclusao_real', a.conclusao_real, 'obs', a.obs, 'marco', a.marco)
                                        order by a.posicao, a.criado_em)
                       from app_crc_acoes a where a.projeto_id = any(v_proj)), '[]'::jsonb),
    'historico', coalesce((select jsonb_agg(jsonb_build_object('id', h.id, 'acao_id', h.acao_id, 'quando', h.quando, 'evento', h.evento,
                                                               'nota', h.nota, 'usuario', h.usuario)
                                            order by h.quando, h.ordem)
                           from app_crc_acao_historico h where h.projeto_id = any(v_proj)), '[]'::jsonb),
    'anexos', coalesce((select jsonb_agg(jsonb_build_object('id', x.id, 'acao_id', x.acao_id, 'nome', x.nome, 'mime', x.mime,
                                                            'tamanho', x.tamanho, 'storage_path', x.storage_path, 'adicionado_em', x.adicionado_em)
                                         order by x.adicionado_em, x.id)
                        from app_crc_anexos x where x.projeto_id = any(v_proj)), '[]'::jsonb)
  );
end;
$$;
revoke all on function public.app_crc_carregar() from public, anon;
grant execute on function public.app_crc_carregar() to authenticated;

-- ---------- anexos (Storage) ----------
-- Bucket privado; o primeiro nível da pasta é o id do projeto, então vale o acesso ao projeto.
insert into storage.buckets (id, name, public, file_size_limit)
values ('app-crc-entregas', 'app-crc-entregas', false, 5242880)
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit;

drop policy if exists app_crc_entregas_select on storage.objects;
drop policy if exists app_crc_entregas_insert on storage.objects;
drop policy if exists app_crc_entregas_update on storage.objects;
drop policy if exists app_crc_entregas_delete on storage.objects;

create policy app_crc_entregas_select on storage.objects for select to authenticated
  using (bucket_id = 'app-crc-entregas' and public.app_crc_acesso((storage.foldername(name))[1]));
create policy app_crc_entregas_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'app-crc-entregas' and public.app_crc_acesso((storage.foldername(name))[1], true));
create policy app_crc_entregas_update on storage.objects for update to authenticated
  using (bucket_id = 'app-crc-entregas' and public.app_crc_acesso((storage.foldername(name))[1], true))
  with check (bucket_id = 'app-crc-entregas' and public.app_crc_acesso((storage.foldername(name))[1], true));
create policy app_crc_entregas_delete on storage.objects for delete to authenticated
  using (bucket_id = 'app-crc-entregas' and public.app_crc_acesso((storage.foldername(name))[1], true));

-- ---------- permissões ----------
-- CRC deixa de ser um menu único ("crc") e passa a ter o submenu Entregas ("crc.entregas").
-- Quem já tinha "crc" recebe o mesmo ver/editar em "crc.entregas".
update public.app_perfis
set permissoes = permissoes || jsonb_build_object('crc.entregas', permissoes -> 'crc')
where permissoes ? 'crc' and not permissoes ? 'crc.entregas';

-- ---------- dados iniciais ----------
insert into public.app_crc_areas (nome) values
  ('APROVAÇÃO'),
  ('CONTABILIDADE'),
  ('CONTROLADORIA'),
  ('CRC'),
  ('CRC/JURIDICO'),
  ('CRC/QUALIDADE'),
  ('DESENV. PRODUTO'),
  ('FINANCEIRO'),
  ('INCORPORAÇÃO'),
  ('INCORPORAÇÃO/APROVAÇÃO'),
  ('JURIDICO'),
  ('JURIDICO/INCORP'),
  ('MKT'),
  ('MKT/CRC'),
  ('OBRA'),
  ('OBRA/JURIDICO'),
  ('PERSONALIZAÇÃO'),
  ('QUALIDADE'),
  ('QUALIDADE/OBRA'),
  ('QUALIDADE/OBRA/CRC')
on conflict (nome) do nothing;

insert into public.app_crc_modelos (id, nome, base, estrutura) values (
  'tpl_base', 'Modelo Base Habitat — Casa Laguna', true,
  '[{"name":"MANUAL DO PROPRIETÁRIO E ÁREA COMUM","actions":[{"name":"COTAÇÃO E FECHAMENTO DA EMPRESA","resps":["QUALIDADE"]},{"name":"ELABORAÇÃO DOS MANUAIS DE USO E OPERAÇÃO","resps":["OBRA"]},{"name":"CONTRATAÇÃO AS BUILT","resps":["OBRA"]},{"name":"ELABORAÇÃO DAS PLANTAS HUMANIZADAS (PROCONSULT) COM MEDIDAS","resps":["QUALIDADE"]},{"name":"VALIDAÇÃO DO MANUAL PELAS AREAS","resps":["QUALIDADE"]},{"name":"ENTREGA MANUAL DO PROPRIETÁRIO","resps":["CRC"]}]},{"name":"DESLIGAMENTO","actions":[{"name":"RELAÇÃO UNIDADES LIBERADAS - VMD","resps":["CONTROLADORIA"]},{"name":"EMISSÃO DE TERMO DE QUITAÇÃO E BAIXA DE HIPOTECA (BANCO)","resps":["CONTROLADORIA"]},{"name":"AVERBAÇÃO DE BAIXA DE HIPOTECA","resps":["JURIDICO"]}]},{"name":"LIGAÇÕES DEFINITIVAS - EQUATORIAL","actions":[{"name":"CARTA DE ORÇAMENTO PARA EXTENSÃO DE REDE","resps":["OBRA/JURIDICO"]},{"name":"PROJETO APROVADO","resps":["INCORPORAÇÃO"]},{"name":"PROTOCOLO DE SOLICITAÇÃO AUTORIZAÇÃO DE LIGAÇÃO AL","resps":["JURIDICO"]},{"name":"POSTE + SUBESTAÇÃO","resps":["OBRA"]},{"name":"VISTORIA EQUATORIAL - LIGAÇÃO EXTENSÃO DE REDE","resps":["OBRA"]},{"name":"CADASTRO IMOVEIS  NA CONCESSIONARIA","resps":["APROVAÇÃO"]},{"name":"TRANSFERENCIA TITULARIDADE ENERGIA","resps":["CRC"]}]},{"name":"LIGAÇÕES DEFINITIVAS - ÁGUA E ESGOTO","actions":[{"name":"ELABORAÇÃO DE PROJETO DE EXTENSÃO DE REDE","resps":["INCORPORAÇÃO"]},{"name":"TENTATIVA DE PARCERIA COM A SANEAGO","resps":["JURIDICO/INCORP"]},{"name":"EXTENSÃO REDE AGUA","resps":["OBRA"]},{"name":"SOLICITAÇÃO LIGAÇÃO DE ESGOTO","resps":["INCORPORAÇÃO"]},{"name":"SOLICITAÇÃO LIGAÇÃO DE ÁGUA","resps":["INCORPORAÇÃO"]},{"name":"CADASTRO IMOVEIS  NA CONCESSIONARIA","resps":["APROVAÇÃO"]},{"name":"POÇO ARTESIANO","resps":["OBRA"]},{"name":"TRANSFERENCIA TITULARIDADE AGUA","resps":["CRC"]}]},{"name":"AMMA","actions":[{"name":"CONTRATAR O RELATÓRIO DE GERENCIAMENTO DE RESÍDUOS E ENVIAR PARA INCORPORADORA FINALIZAR O PROCESSO DE LICENÇA DE INSTALAÇÃO (LI) NA AMMA","resps":["APROVAÇÃO"]},{"name":"LI - PROTOCOLAR REQUERIMENTO SUGERINDO NA AMMA, JUNTAMENTE COM O PROJETO DA CALÇADA E UMA SUGESTÃO DO PAISAGISMO QUANTO AO TIPO DE PLANTA","resps":["APROVAÇÃO"]},{"name":"EXECUTAR CALÇADA - INCLUSIVE PLANTAR MUDAS E PISO ACESSÍVEL","resps":["OBRA"]},{"name":"VISTORIA AMMA PARA HABITE-SE/CERTIDÃO AMMA","resps":["APROVAÇÃO"]}]},{"name":"BOMBEIROS","actions":[{"name":"REAPROVAÇÃO O PROJETO DE BOMBEIROS","resps":["INCORPORAÇÃO"]},{"name":"RESPONSÁVEL PASSAR DIRETRIZES DO QUE PRECISA ESTAR PRONTO PARA VISTORIA DO BOMBEIRO","resps":["OBRA"]},{"name":"PROTOCOLO PROCESSO BOMBEIRO","resps":["APROVAÇÃO"]},{"name":"ENVIO DO COMPROVANTE DE PAGAMENTO PARA RESPONSÁVEL","resps":["FINANCEIRO"]},{"name":"1ª VISTORIA DO BOMBEIRO","resps":["OBRA"]},{"name":"2ª VISTORIA DO BOMBEIRO","resps":["OBRA"]},{"name":"EMISSÃO DA CERTIDÃO BOMBEIRO","resps":["OBRA"]}]},{"name":"HABITE-SE PREFEITURA","actions":[{"name":"PROTOCOLOCAR PROCESSO DE HABITE-SE","resps":["APROVAÇÃO"]},{"name":"1ª VISTORIA DE HABITE-SE PREFEITURA","resps":["OBRA"]},{"name":"REAPROVAÇÃO PROJETO DE ARQUITETURA (DEP PROJETOS / PERSONALIZAÇÃO)","resps":["INCORPORAÇÃO"]},{"name":"2ª VISTORIA DO HABITE-SE","resps":["OBRA"]},{"name":"CERTIDÃO DE HABITE-SE","resps":["OBRA"]},{"name":"AVERBAÇÃO CERTIDÃO DE HABITE-SE","resps":["APROVAÇÃO"]}]},{"name":"DOCUMENTAÇÃO","actions":[{"name":"PREENCHIMENTO QUADRO DE ÁREAS","resps":["INCORPORAÇÃO"]},{"name":"MODELO DE FECHAMENTO VARANDA E DEFINIÇÃO SE AS SACADAS PODERÃO SER INTEGRADAS","resps":["QUALIDADE/OBRA/CRC"]},{"name":"ABRIR PROCESSO DE ALTERAÇÃO DE ITU PARA IPTU (CERTIDÕES DE LANÇAMENTO) - VIRTUAL E DEFINITIVA","resps":["APROVAÇÃO"]},{"name":"FINANCEIRO FORNECER DOCUMENTAÇÃO PARA ISS","resps":["FINANCEIRO"]},{"name":"PROTOCOLO CÁLCULO DO ISS/LIBERAÇÃO ISS","resps":[]},{"name":"RETIFICAR MEMORIAL DE INCORPORAÇÃO - VAGAS","resps":[]},{"name":"CERTIDÃO DE LANÇAMENTO DE IPTU - PARA AVERBAÇÃO","resps":["APROVAÇÃO"]},{"name":"CND-INSS","resps":["CONTABILIDADE"]},{"name":"REVISAR MINUTA CONVENÇÃO DE CONDOMÍNIO","resps":["JURIDICO"]},{"name":"ADITIVO CONTRATO DE FINANCIAMENTO DA OBRA - AVERBAÇÃO NA MATRÍCULA","resps":["FINANCEIRO"]},{"name":"EMISSÃO DE CONTRATOS DE CLIENTE - AVERBAÇÃO MATRÍCULA (PILOTO FB)","resps":["CRC"]},{"name":"LAUDO AVALIAÇÃO UNIDADES (BANCO)","resps":["CRC"]},{"name":"PASTA MAE PARA FB (BANCO)","resps":["CRC"]},{"name":"PROTOCOLO DA CONVENÇÃO E INSTITUIÇÃO DO CONDOMÍNIO (NO MOMENTO DA AVERBAÇÃO)","resps":["JURIDICO"]}]},{"name":"VISTORIA INTERNA OBRA","actions":[{"name":"MONTAR CHECK LIST","resps":["QUALIDADE"]},{"name":"TREINAMENTO EQUIPE PARA VISTORIA","resps":["QUALIDADE"]},{"name":"CHECK LIST PERSONALIZAÇÃO","resps":["PERSONALIZAÇÃO"]}]},{"name":"VISTORIA INTERNA - CRC E QUALIDADE","actions":[{"name":"VISTORIA PREVIA DE AREA COMUM","resps":["OBRA"]}]},{"name":"ORGANIZAÇÃO PARA ENTREGA","actions":[{"name":"GESTÃO DESLIGAMENTO FINANCEIRO","resps":["CRC"]},{"name":"DEFINIÇÃO E AQUISIÇÃO DE BRINDE PARA ENTREGA AO CLIENTE","resps":["MKT"]},{"name":"LAUDO VISTORIA PRIME ADMINISTRADORA","resps":["CRC"]},{"name":"REPAROS AREA COMUM LAUDO PRIME","resps":["OBRA"]}]},{"name":"MONTAGEM AREA COMUM ÁREA COMUM","actions":[{"name":"FABRICAÇÃO DA MARCENARIA","resps":["OBRA"]},{"name":"ASSINATURA DO CADERNO TÉCNICO - FECHAR MATERIAL DE VENDA COMO O QUE SERÁ ENTREGUE","resps":["DESENV. PRODUTO"]},{"name":"MONTAGEM ÁREA COMUM","resps":["DESENV. PRODUTO"]},{"name":"RECEBIMENTO INTERNO DA MONTAGEM DAS AREAS COMUNS","resps":["DESENV. PRODUTO"]},{"name":"MONTAGEM ACADEMIA","resps":["DESENV. PRODUTO"]},{"name":"MONTAGEM E INSTALAÇÃO GERADOR","resps":["OBRA"]},{"name":"MANUTENÇÃO E TESTE GERADOR","resps":["OBRA"]},{"name":"MANUTENÇÃO ELEVADORES","resps":["OBRA"]},{"name":"INSTALAÇÃO QR CODE DO MANUAL DO PROPRIETARIO E SINDICO","resps":["CRC/QUALIDADE"]},{"name":"IMPLANTAÇÃO E TESTE SISTEMA DE MONITORAMENTO","resps":["OBRA"]},{"name":"IMPLANTAÇÃO E TESTE SISTEMA DE ACESSO","resps":["OBRA"]}]},{"name":"VISTORIAS DE UNIDADES PRIVATIVAS","actions":[{"name":"LIBERAÇÃO UNIDADES PARA VISTORIA DA QUALIDADE","resps":["OBRA"]},{"name":"LIBERAÇÃO UNIDADES PARA VISTORIA DO CLIENTE","resps":["QUALIDADE"]},{"name":"EQUIPE SUPORTE OBRA PARA MOMENTO VISTORIA","resps":["OBRA"]},{"name":"PREPARAÇÃO DA UNIDADE PARA VISTORIA COM O CLIENTE","resps":["OBRA"]},{"name":"VISTORIA COM O CLIENTE","resps":["CRC/QUALIDADE"]}]},{"name":"VISTORIA AREA COMUM","actions":[{"name":"CHECK LIST OBRA","resps":["QUALIDADE"]},{"name":"INVENTARIO","resps":["DESENV. PRODUTO"]},{"name":"PREPARAÇÃO DAS AREAS PARA VISTORIA COM O CONDOMINIO","resps":["OBRA"]},{"name":"AGENDAMENTO DE VISTORIA COM SINDICO E REPRESENTANTES","resps":["CRC"]},{"name":"VISTORIA","resps":["CRC/QUALIDADE"]},{"name":"TERMO DE ACORDO DE ENTREGA","resps":["JURIDICO"]}]},{"name":"ENTREGA DE CHAVES","actions":[{"name":"DESLISGAMENTO/ESCRITURAÇÃO CLIENTE","resps":["CRC"]},{"name":"FORMALIZAÇÃO DA ENTREGA - ASSINATURA TERMO DE ENTREGA","resps":["CRC"]}]},{"name":"COMUNICAÇÃO VISUAL","actions":[{"name":"PROGRAMAR FOTOS E VIDEO DA ÁREA COMUM FINALIZADA E PRODUÇÃO","resps":["MKT"]},{"name":"COMUNICAÇÃO VISUAL DO EMPREENDIMENTO - ARTE","resps":["MKT"]},{"name":"INSTALAÇÃO DA PLACA DE TOPO DO PRÉDIO","resps":["MKT"]},{"name":"IDENTIFICAÇÃO AREA COMUNS E UNIDADES","resps":["MKT"]},{"name":"TOTEM E COMUNICAÇÃO NA FACHADA","resps":["MKT"]},{"name":"INSTALAR NUMERAÇÃO DA OBRA","resps":["MKT"]}]},{"name":"EVENTO","actions":[{"name":"VISTORIA DE PERSONALIZAÇÃO","resps":["PERSONALIZAÇÃO"]},{"name":"EVENTO DE INSTALAÇÃO DO ELEVADOR","resps":["CRC"]},{"name":"VISITA CLIENTE PARA MEDIÇÃO DE ARMARIO","resps":["CRC"]},{"name":"ELABORAR EVENTO DE ENTREGA","resps":["MKT"]},{"name":"CONVITES IMPRESSOS/DIGITAL PARA EVENTO DE ENTREGA","resps":["MKT/CRC"]},{"name":"COMUNICAÇÃO COM CLIENTE","resps":["CRC"]},{"name":"DIA DO EVENTO DE ENTREGA","resps":["MKT/CRC"]}]},{"name":"ASSEMBLEIA/ENTREGA","actions":[{"name":"EDITAL CONVOCAÇÃO ASSEMBLEIA","resps":["JURIDICO"]},{"name":"DISPARO EDITAL","resps":["CRC"]},{"name":"VIDEO EVOLUÇÃO DA OBRA","resps":["MKT"]},{"name":"TEMPLATE E APRESENTAÇÃO ASSEMBLEIA","resps":["MKT"]},{"name":"PREVISÃO ORÇAMENTARIA","resps":["CRC"]},{"name":"ASSEMBLEIA","resps":["CRC/JURIDICO"]},{"name":"ENTREGA DA DOCUMENTAÇÃO/PROJETOS QUE SERÁ FORNECIDA AO SÍNDICO","resps":["QUALIDADE"]},{"name":"ENTREGA DAS NOTAS FISCAIS E INVENTÁRIO/TERMO DE RECEBIMENTO DO MOBILIÁRIO DA COMUM","resps":["DESENV. PRODUTO"]},{"name":"TREINAMENTO SÍNDICO E ZELADOR (EMPRESAS QUE EXECUTARAM OS SERVIÇOS)","resps":["QUALIDADE/OBRA/CRC"]},{"name":"INSTITUIÇÃO E AVERBAÇÃO DO CONDOMÍNIO","resps":["JURIDICO"]},{"name":"DEFINIÇÃO E CONTRATAÇÃO ADMINISTRADORA","resps":["CRC/JURIDICO"]},{"name":"PROJETO DE COMO SERÁ CORTINA DE VIDRO (COM DETALHAMENTO ALINHADO COM A OBRA)","resps":["DESENV. PRODUTO"]},{"name":"ACOMPANHAR IMPLANTAÇÃO DE CRONOGRAMA DE MANUTENÇÕES","resps":["CRC/QUALIDADE"]}]},{"name":"QUALIDADE","actions":[{"name":"AREAS APRESENTAREM LIÇÕES APRENDIDAS","resps":[]}]}]'::jsonb
) on conflict (id) do nothing;
